# Replace with your key details and model information
key-details:
  SPACE_KEY: <YOUR_ARIZESPACE_KEY>
  API_KEY: <YOUR_ARIZEAPI_KEY>
model-details:
  MODEL_ID: <YOUR_MODEL_NAME>
  MODEL_VERSION: <YOUR_MODEL_VERSION>
image-base-url: <BASE_URL_FOR_THE_IMAGES>
